# Generated by Django 3.2.8 on 2021-10-20 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='rooms')),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(choices=[('', 'Choose Type'), ('executive', 'Executive'), ('suite', 'Suite')], default='Choose Type', max_length=30)),
                ('person_capacity', models.IntegerField()),
                ('floor', models.CharField(choices=[('', 'Choose'), ('ground floor', 'Ground Floor'), ('first floor', 'First Floor')], default='Choose', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
