# Generated by Django 3.2.8 on 2021-10-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
    ]
