# Generated by Django 3.2.8 on 2021-10-24 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20211024_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
