# Generated by Django 3.2.8 on 2021-10-26 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookedroom_bookingdetail_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
