# Generated by Django 3.2.8 on 2021-10-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('bookings', '0007_auto_20211026_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_detail', to='customers.customer'),
        ),
    ]
